import { build } from 'esbuild';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

// Embed complete HTML in TS modules so Mastra's production bundle needs no asset paths.
const apps = new URL('../src/apps/', import.meta.url);
const output = new URL('../src/mastra/mcp/generated/', import.meta.url);
await mkdir(output, { recursive: true });
for (const entry of await readdir(apps, { withFileTypes: true })) {
  if (!entry.isDirectory() || entry.name === 'shared') continue;
  const directory = new URL(`${entry.name}/`, apps);
  const { outputFiles } = await build({
    entryPoints: [new URL('app.ts', directory).pathname],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    alias: {
      '@modelcontextprotocol/client/_shims': fileURLToPath(new URL('mcp-browser-shim.mjs', import.meta.url)),
    },
    target: 'es2022',
    minify: true,
    write: false,
  });
  const css = await readFile(new URL('shared/style.css', apps), 'utf8');
  const template = await readFile(new URL('index.html', directory), 'utf8');
  const script = outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
  const html = template.replace('<!-- APP_STYLES -->', () => `<style>${css}</style>`)
    .replace('<!-- APP_SCRIPT -->', () => `<script>${script}</script>`);
  await writeFile(new URL(`${entry.name}.ts`, output),
    `// Generated by npm run build:apps. Edit src/apps/${entry.name} instead.\nexport default ${JSON.stringify(html)};\n`);
  console.log(`Built ${entry.name} (${Math.round(Buffer.byteLength(html) / 1024)} KB)`);
}
